### ISSUE TITLE
Error in Samsung Internet

### ISSUE THREAD

**Issue by gutuxa** [lancedikson/bowser#313]
Bowser throw error "Cannot read property 'toLowerCase' of undefined" in Samsung Internet.

window.navigator.userAgent :
<img width="343" alt="Screen Shot 2019-04-11 at 6 50 50 PM" src="https://user-images.githubusercontent.com/4046566/55971809-de84d400-5c8a-11e9-85e6-4912cd70ee94.png">

Method:
Bowser.getParser(window.navigator.userAgent)

**Comment by lancedikson** [comment]
Hi, @gutuxa. Could you, please, copy-paste the UserAgent string as text here, it's hard to debug with a picture as a source. Also, do you know the error stack? It would help if you knew the place of the error.

**Comment by gutuxa** [comment]
Hi! Sorry for screenshot.

UserAgent like this
Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-G930F Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/9.0 Chrome/67.0.3396.87 Mobile Safari/537.36
or
Mozilla/5.0 (Linux; Android 8.1.0; SAMSUNG SM-T580 Build/M1AJQ) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/8.2 Chrome/63.0.3239.111 Safari/537.36

Stack is
TypeError: Cannot read property 'toLowerCase' of undefined
  at t.value(/static/vendor.ee2f113b.js:70:13557)
  at ? (/static/vendor.ee2f113b.js:70:13303)
  at Array.find(/static/vendor.ee2f113b.js)
  at t.value(/static/vendor.ee2f113b.js:70:13277)
  at t.value(/static/app.2dd6da75.js:1:331633)
  at Ha(/static/vendor.ee2f113b.js:102:82387)
  at qa(/static/vendor.ee2f113b.js:102:85062)
  at ? (/static/vendor.ee2f113b.js:102:98269)
  at Object.e.unstable_runWithPriority(/static/vendor.ee2f113b.js:111:3194)
  at Au(/static/vendor.ee2f113b.js:102:98204)
  at Mu(/static/vendor.ee2f113b.js:102:97980)
  at ju(/static/vendor.ee2f113b.js:102:97325)
  at Su(/static/vendor.ee2f113b.js:102:96346)
  at Qa(/static/vendor.ee2f113b.js:102:95220)
  at Bu(/static/vendor.ee2f113b.js:102:99235)
  at Fu(/static/vendor.ee2f113b.js:102:99289)
  at Uu.render(/static/vendor.ee2f113b.js:102:103080)
  at ? (/static/vendor.ee2f113b.js:102:100935)
  at Nu(/static/vendor.ee2f113b.js:102:98511)
  at Wu(/static/vendor.ee2f113b.js:102:100868)
  at Object.hydrate(/static/vendor.ee2f113b.js:102:104025)
  at ? (/static/app.2dd6da75.js:1:690730)
  at ? (<anonymous>)

**Comment by Rakiiv** [comment]
I have this issue too, and it seems it occurs only on Samsung Browser, but I didn't test all possible devices.
Imho it is this line: https://github.com/lancedikson/bowser/blob/19288762f1bb18f319f7658a3d3e1672eca02843/src/parser.js#L410
There is a toLowerCase on the return value of getBrowserAlias. It seems this function returns undefined.
I switched back to the last version until this is fixed.

**Comment by lancedikson** [comment]
Thanks for the information, seems like a bug brought by the latest release. I will try to find it today.

**Comment by lancedikson** [comment]
I've fixed the issue and released it as 2.2.1
